-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 22:57:21 2025
-- Model: Modelo Relacional - Cursos    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`INSTITUICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTITUICAO` (
  `id_instituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` TEXT NOT NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSO` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `carga_horaria` DOUBLE NOT NULL,
  `id_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_CURSO_INSTITUICAO1_idx` (`id_instituicao` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_INSTITUICAO1`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `mydb`.`INSTITUICAO` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESSOR` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `curso(s)` TEXT NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(45) NOT NULL,
  `id_curso` INT NOT NULL,
  `id_professor` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_TURMA_CURSO1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_TURMA_PROFESSOR1_idx` (`id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_TURMA_CURSO1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`CURSO` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_PROFESSOR1`
    FOREIGN KEY (`id_professor`)
    REFERENCES `mydb`.`PROFESSOR` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TURMA_ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TURMA_ALUNO` (
  `id_turma` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_turma`, `id_aluno`),
  INDEX `fk_TURMA_has_ALUNO_ALUNO1_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `fk_TURMA_has_ALUNO_TURMA_idx` (`id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_TURMA_has_ALUNO_TURMA`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`TURMA` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TURMA_has_ALUNO_ALUNO1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `mydb`.`ALUNO` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
